server:
  port: 8060
  servlet:
    context-path: /official

spring:
  main:
    allow-circular-references: true
  datasource:
#    url: jdbc:mysql://localhost:3306/library
    url: jdbc:mysql://lib_mysql:3306/library
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

integrations:
  personal-data:
    scheme: http
    host: localhost
    port: 48884
    timeout: 10000

super-admin:
  login: admin
  password: admin